apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "makit.fullname" . }}
  labels: {{- include "makit.labels" . | nindent 4 }}
data:
  shield.yaml: |
{{ include "makit.shieldYAML" . | indent 4 }}
