{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "makit.fullname" . }}
  labels: {{- include "makit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "makit.selector" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
